
- name: "kubectl download & install v1.2"
  get_url:
    url: "https://dl.k8s.io/release/v1.22.0/bin/linux/amd64/kubectl"
    dest: "${HOME}/.kubectl"
    checksum: "sha256:703e70d49b82271535bc66bc7bd469a58c11d47f188889bd37101c9772f14fa1"
    mode: '0755'
  become: true

- name: "aws-vault - set completions in .bashrc"
  lineinfile:
    path: '${HOME}/.bashrc'
    state: present
    line: "\n# kubectl config\nsource <(kubectl completion bash)"

- name: "aws-vault - set completions in .zshrc"
  lineinfile:
    path: '${HOME}/.zshrc'
    state: present
    line: "\n# kubectl config\nsource <(kubectl completion zsh)"
